pihi/pihi/__init__.py
import os
import logging
import logging.handlers

from pathlib import Path

from flask import Flask

APP_PATH = Path(__file__).parent

app = Flask(__name__)

from pihi.views import basic

# Initialise blueprints after the views have been imported to correctly register endpoints
from pihi.blueprints import api

import pihi.platform

if __name__ != "__main__":
    gunicorn_logger = logging.getLogger("gunicorn.error")
    app.logger.handlers = gunicorn_logger.handlers
    app.logger.setLevel(gunicorn_logger.level)

api.init_app(app)

pihi/pihi/blueprints/api.py
import logging
import json

from flask import Flask, Blueprint, request, jsonify
from flask_sse import sse

from pihi import app
from pihi import platform

logger = logging.getLogger(__name__)

api = Blueprint('api', __name__)

@api.route("/api/gpio/<gpio>/set", methods=['POST'])
def set_gpio(gpio):
    if request.method == 'POST':
        content = request.get_json()
        requested_state = content["requested_state"]

        this_platform = platform.get_platform()

        if this_platform.gpio_interface:
            gpio = int(gpio)
            this_platform.gpio_interface.setup(gpio, this_platform.gpio_interface.OUT)
            this_platform.gpio_interface.output(gpio, requested_state)
            actual_state = this_platform.gpio_interface.input(gpio)
        else:
            logger.info("No platform interface to set %d to %d", gpio, 1 if requested_state else 0)
            actual_state = requested_state

        return jsonify({"state": actual_state})

@app.route('/hello')
def publish_hello():
    sse.publish({"message": "Hello!"}, type='greeting')
    return "Message sent!"

def init_app(app):
    app.config["REDIS_URL"] = "redis://localhost"
    app.register_blueprint(api)
    app.register_blueprint(sse, url_prefix='/stream')

pihi/pihi/views/basic.py
import logging

from flask import render_template

from pihi import app
from pihi import platform

@app.route('/')
def index():

    this_platform = platform.get_platform()

    return render_template("index.html", platform=this_platform)

pihi/pihi/templates/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>PiHi</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='grid.css') }}">
</head>
<body>
  <h1>PiHi</h1>

  <p>Platform: {{ platform.name }}</p>

  <div class="gridcontainer">
    <h2>GPIO</h2>
    <div id="gpiobox">
    
      {% for gpio in platform.gpio_nums %}
      <div class="griditem">
        <onoff_button id='gpio{{ "%02d" | format(gpio) }}'></onoff_button>
      </div>
      {% endfor %}

    </div>

    <h2>Comms</h2>
    <div id="commsbox">
      <div class="griditem">
        <comms_sse id='i2c'></comms_sse>
      </div>
    </div>

  </div>

  <script src="{{ url_for('static', filename='onoff_button.tag') }}" type="riot"></script>
  <script src="{{ url_for('static', filename='comms_sse.tag') }}" type="riot"></script>
  <script src="https://cdn.jsdelivr.net/npm/riot@4/riot+compiler.min.js"></script>

  <script>
    riot.compile().then(() => {
      {% for gpio in platform.gpio_nums %}
      riot.mount(
        'onoff_button#gpio{{ "%02d" | format(gpio) }}',
        {
          set_gpio_url: '{{ url_for("api.set_gpio", gpio=gpio) }}',
          text: 'GPIO{{ "%02d" | format(gpio) }}'
        }
      );
      {% endfor %}

      riot.mount(
        'comms_sse#i2c',
        {
          sse_url: '{{ url_for("sse.stream") }}',
        }
      );
    });
  </script>
</body>
</html>